[build]
  publish = "public"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/nails/*"
  to = "/nails/:splat.html"
  status = 200
  force = true

[[redirects]]
  from = "/gems/*"
  to = "/gems/:splat.html"
  status = 200
  force = true

# Handle www to non-www redirect
[[redirects]]
  from = "https://www.bookbuy.ca/*"
  to = "https://bookbuy.ca/:splat"
  status = 301
  force = true

# Handle HTTP to HTTPS redirect
[[redirects]]
  from = "http://bookbuy.ca/*"
  to = "https://bookbuy.ca/:splat"
  status = 301
  force = true

# Handle /lander redirect to homepage
[[redirects]]
  from = "/lander"
  to = "/"
  status = 301
  force = true

# Handle /index.html redirect to homepage
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true


