[build]
  publish = "public"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/nails/*"
  to = "/nails/:splat.html"
  status = 200

[[redirects]]
  from = "/gems/*"
  to = "/gems/:splat.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
