[build]
  publish = "public"
  command = ""

[[redirects]]
  from = "/nails/*"
  to = "/nails/:splat.html"
  status = 200

[[redirects]]
  from = "/gems/*"
  to = "/gems/:splat.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
